language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dmalvania/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true dmalvania/docker-react npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "doker-react"
  env: "DokerReact-env"
  bucker_name: "elasticbeanstalk-us-west-2-849905330246"
  bucker_path: "doker-react"
  on: 
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY